title: Platform of Things
description: Articles and Things

theme: just-the-docs

url: ""
baseurl: ""

permalink: /:year/:month/:day/:title:output_ext

# Enable search
search_enabled: true

# Aux links (top right)
aux_links:
  "GitHub":
    - "https://github.com/rexchoppers"
  "LinkedIn":
    - "https://www.linkedin.com/in/connor-brady-50984311b"

aux_links_new_tab: true

# Color scheme (light, dark, or custom)
color_scheme: dark

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

