title: Platform of Things
description: Articles and Things

theme: just-the-docs

url: ""
baseurl: ""

# Enable search
search_enabled: true

# Aux links (top right)
aux_links:
  "View on GitHub":
    - "https://github.com/your-username/platform-of-things-articles"

# Color scheme (light, dark, or custom)
color_scheme: dark

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

